import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { ProjectData } from '../data/project'
import type { StoryPlayer, StoryPlayerState } from './storyPlayer'
import type { Story, StoryAppOperations, StoryStep } from './storyTypes'
import { DEFAULT_CAMERA_DURATION_MS } from './storyTimeline'
import { authoredStepDuration, seekStoryPreview } from './storyTimingEditor'
import { createEditorModel, currentViewStep, deleteStep, duplicateStep, insertStep, reorderStep, toStory, updateStep } from './storyEditorState'
import { downloadStory, saveStoryToSource } from './storySerialization'

const ACTION_NAMES: Record<StoryStep['action'], string> = { show:'Show',hide:'Hide',activate:'Activate',deactivate:'Deactivate',wait:'Wait',setView:'View',setBasemap:'Basemap',setOverlay:'Overlay',setDarkMode:'Dark mode',setDarkBasemap:'Dark basemap',selectJurisdiction:'Jurisdiction',clearJurisdiction:'Clear jurisdiction',showJurisdiction:'Show region',activateJurisdiction:'Activate region',hideJurisdiction:'Hide region' }
const summary = (step: StoryStep, names: Map<string,string>) => { if ('snapshotDate' in step) return `${step.name} · ${step.snapshotDate.slice(0,4)}`; if ('id' in step) return names.get(step.id) ?? step.id; if (step.action === 'setView') return step.label ?? `${step.center[0].toFixed(4)}, ${step.center[1].toFixed(4)}`; if ('value' in step) return String(step.value); if (step.action === 'setOverlay') return `${step.layer} ${step.visible ? 'ON' : 'OFF'}`; return step.label ?? '' }
const numeric = (value: string) => Number(value)
const RATE_OPTIONS = [0.5,1,2,4]
const DURATION_PRESETS = [0.5,0.8,1,1.5,2]

export function StoryEditor({ story, project, operations, player, state, onChange, onInsertReady }: { story: Story; project: ProjectData; operations: StoryAppOperations; player: StoryPlayer; state: StoryPlayerState; onChange(story: Story): void; onInsertReady?(insert:((step:StoryStep)=>void)|null):void }) {
  const [model,setModel]=useState(()=>createEditorModel(story)); const [open,setOpen]=useState(true); const drag=useRef<number|null>(null)
  const modelRef=useRef(model); modelRef.current=model
  const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const [saveMessage,setSaveMessage]=useState('')
  const names=useMemo(()=>new Map(project.searchable.map((feature)=>[feature.properties.id,feature.properties.name])),[project])
  const commit=useCallback((next:ReturnType<typeof createEditorModel>)=>{player.pause();modelRef.current=next;setModel(next);onChange(toStory(next));setSaveState('idle');setSaveMessage('')},[onChange,player])
  const insertExternal=useCallback((step:StoryStep)=>commit(insertStep(modelRef.current,step)),[commit])
  useEffect(()=>{onInsertReady?.(insertExternal);return()=>onInsertReady?.(null)},[insertExternal,onInsertReady])
  const selectedIndex=model.steps.findIndex(({key})=>key===model.selectedKey); const selected=model.steps[selectedIndex]
  const edit=(patch:Record<string,unknown>)=>selected&&commit(updateStep(model,selected.key,{...selected.step,...patch} as StoryStep))
  const save=async()=>{setSaveState('saving');setSaveMessage('');try{const result=await saveStoryToSource(toStory(model));setSaveState('saved');setSaveMessage(`Saved ${result.path}`)}catch(error){setSaveState('error');setSaveMessage(error instanceof Error?error.message:String(error))}}
  const presets=(apply:(duration:number)=>void)=><div className="story-duration-presets"><span>Presets</span>{DURATION_PRESETS.map(value=><button key={value} onClick={()=>apply(value)}>{value.toFixed(1)}</button>)}</div>
  return <section className="story-editor" aria-label="Story authoring pane"><header className="story-editor-title"><button aria-expanded={open} onClick={()=>setOpen(!open)}>{open?'▾':'▸'}</button><strong>STORY — {story.displayName??story.id}</strong></header>{open&&<>
    <div className="story-playback"><button onClick={()=>void player.restart()}>Restart</button><button onClick={()=>void player.previous()}>Previous</button><button onClick={()=>state.status==='playing'?player.pause():void player.play()}>{state.status==='playing'?'Pause':'Play'}</button><select aria-label="Preview speed" value={state.playbackRate} onChange={event=>player.setPlaybackRate(Number(event.target.value))}>{RATE_OPTIONS.map(rate=><option key={rate} value={rate}>{rate}×</option>)}</select><button onClick={()=>void player.next()}>Next</button><small>{state.elapsedSeconds.toFixed(3)} / {state.totalWaitDuration.toFixed(3)} s · Step {Math.min(state.currentStepIndex+1,story.steps.length)} / {story.steps.length}</small></div>
    <label className="story-scrubber"><span>0.000</span><input aria-label="Story time" type="range" min="0" max={player.getDuration()} step="0.001" value={Math.min(state.elapsedSeconds,player.getDuration())} onChange={event=>void seekStoryPreview(player,Number(event.target.value))}/><span>{player.getDuration().toFixed(3)}</span><output>{state.elapsedSeconds.toFixed(3)} s</output></label>
    <ol className="story-step-list">{model.steps.map((entry,index)=>{const duration=authoredStepDuration(entry.step);const start=(player.timeline.stepBoundariesMs[index]??0)/1000;return <li key={entry.key} className={entry.key===model.selectedKey?'selected':''} draggable onDragStart={()=>{drag.current=index}} onDragOver={(event)=>event.preventDefault()} onDrop={()=>{if(drag.current!==null)commit(reorderStep(model,drag.current,index));drag.current=null}} onClick={()=>setModel({...model,selectedKey:entry.key})}><span className="drag" title="Drag to reorder">≡</span><b>{String(index+1).padStart(2,'0')}</b><time>{start.toFixed(3)}</time><span><strong>{ACTION_NAMES[entry.step.action]}</strong><small>{summary(entry.step,names)}</small></span><em>{duration===null?'':`${duration.toFixed(1)} s`}</em><button title="Duplicate" aria-label={`Duplicate step ${index+1}`} onClick={(event)=>{event.stopPropagation();commit(duplicateStep(model,entry.key))}}>⧉</button><button title="Delete" aria-label={`Delete step ${index+1}`} onClick={(event)=>{event.stopPropagation();commit(deleteStep(model,entry.key))}}>×</button></li>})}</ol>
    <div className="story-author-actions"><button onClick={()=>commit(insertStep(model,currentViewStep(operations.getCurrentView())))}>+ Current View</button><button onClick={()=>commit(insertStep(model,{action:'wait',duration:2}))}>+ Wait</button><button disabled={!selected} onClick={()=>selected&&void player.previewStep(selectedIndex)}>Preview selected</button><button disabled={!selected} onClick={()=>selected&&void player.playFrom(selectedIndex)}>Preview from here</button><button disabled={saveState==='saving'} onClick={()=>void save()}>{saveState==='saving'?'Saving…':saveState==='saved'?'Saved ✓':'Save / Update Story'}</button><button onClick={()=>downloadStory(toStory(model))}>Download Story JSON</button></div>
    {saveMessage&&<small className={saveState==='error'?'story-error':'story-save-status'}>{saveMessage}</small>}
    {selected?.step.action==='activate'&&<div className="story-details"><strong>Activate details</strong><label>Target<input value={names.get(selected.step.id)??selected.step.id} readOnly/></label><label>Camera duration<input type="number" min="0" step="0.1" value={selected.step.cameraDuration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={event=>edit({cameraDuration:numeric(event.target.value)})}/></label>{presets(duration=>edit({cameraDuration:duration}))}</div>}
    {selected?.step.action==='activateJurisdiction'&&<div className="story-details"><strong>Activate region details</strong><label>Target<input value={`${selected.step.name} · ${selected.step.snapshotDate}`} readOnly/></label><label>Camera duration<input type="number" min="0" step="0.1" value={selected.step.cameraDuration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={event=>edit({cameraDuration:numeric(event.target.value)})}/></label>{presets(duration=>edit({cameraDuration:duration}))}</div>}
    {selected?.step.action==='setView'&&<div className="story-details"><strong>View details</strong><label>Label<input value={selected.step.label??''} onChange={e=>edit({label:e.target.value||undefined})}/></label><label>Duration<input type="number" min="0" step="0.1" value={selected.step.duration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={e=>edit({duration:numeric(e.target.value)})}/></label><label>Longitude<input type="number" step="0.000001" value={selected.step.center[0]} onChange={e=>edit({center:[numeric(e.target.value),selected.step.action==='setView'?selected.step.center[1]:0]})}/></label><label>Latitude<input type="number" step="0.000001" value={selected.step.center[1]} onChange={e=>edit({center:[selected.step.action==='setView'?selected.step.center[0]:0,numeric(e.target.value)]})}/></label><label>Zoom<input type="number" step="0.001" value={selected.step.zoom} onChange={e=>edit({zoom:numeric(e.target.value)})}/></label><label>Bearing<input type="number" step="0.01" value={selected.step.bearing} onChange={e=>edit({bearing:numeric(e.target.value)})}/></label><label>Pitch<input type="number" min="0" max="85" step="0.01" value={selected.step.pitch} onChange={e=>edit({pitch:numeric(e.target.value)})}/></label>{presets(duration=>edit({duration}))}</div>}
    {selected?.step.action==='wait'&&<div className="story-details"><strong>Wait details</strong><label>Duration<input type="number" min="0" step="0.1" value={selected.step.duration} onChange={e=>edit({duration:numeric(e.target.value)})}/></label>{presets(duration=>edit({duration}))}</div>}
    {state.error&&<em className="story-error">{state.error}</em>}
  </>}</section>
}
