import { describe,it,expect,vi } from 'vitest'
import type { ProjectData } from '../data/project'
import type { EvaluatedStoryState } from './storyTimeline'
import type { StoryAppOperations,StoryAppSnapshot } from './storyTypes'
import { StoryPlayer,type StoryClock } from './storyPlayer'
const baseline:StoryAppSnapshot={selected:[],activeFeature:null,basemap:'presentation',layers:{basemap:'presentation',darkBasemap:false,modernRoads:true,railways:true,stations:true,historicalRoads:true,historicalPosts:true,jurisdictions:false},darkMode:'auto',jurisdiction:null,camera:{center:[0,0],zoom:10,bearing:0,pitch:0}}
const feature={type:'Feature',properties:{id:'A',name:'A',type:'place'},geometry:{type:'Point',coordinates:[10,10]}} as const
const harness=()=>{const frames:EvaluatedStoryState[]=[];const operations:StoryAppOperations={snapshot:()=>structuredClone(baseline),restore:()=>{},showFeature:()=>{},hideFeature:()=>{},activateFeature:()=>{},deactivateFeature:()=>{},setBasemap:()=>{},setOverlayVisibility:()=>{},setDarkMode:()=>{},setManualDarkBasemap:()=>{},selectJurisdiction:()=>{},clearJurisdiction:()=>{},getCurrentView:()=>baseline.camera,setView:()=>{},resolveFeatureCameraTarget:(_feature,_visible,from)=>({...from,center:[10,10],zoom:15}),applyStoryFrame:frame=>{frames.push(structuredClone(frame))},waitForRender:vi.fn(async()=>{})};return{frames,operations}}
describe('deterministic Story player',()=>{
 it('seeks idempotently and exposes duration/time/render barrier',async()=>{const {frames,operations}=harness();const player=new StoryPlayer({id:'x',project:'x',steps:[{action:'show',id:'A'},{action:'activate',id:'A',cameraDuration:1},{action:'wait',duration:2}]},{searchable:[feature]} as unknown as ProjectData,operations);expect(player.getDuration()).toBe(3);await player.seek(1.4);const a=frames.at(-1);await player.seek(.2);await player.seek(1.4);expect(frames.at(-1)).toEqual(a);expect(player.getTime()).toBe(1.4);await player.waitForRender();expect(operations.waitForRender).toHaveBeenCalled()})
 it('uses the same evaluated frames for autoplay and explicit seek',async()=>{vi.useFakeTimers();let now=0;const clock:StoryClock={now:()=>now,schedule:(cb)=>setTimeout(cb,16),cancel:id=>clearTimeout(id as number)};const first=harness();const player=new StoryPlayer({id:'x',project:'x',steps:[{action:'activate',id:'A',cameraDuration:1}]},{searchable:[feature]} as unknown as ProjectData,first.operations,clock);void player.play();await Promise.resolve();now=500;await vi.advanceTimersByTimeAsync(16);const autoplay=first.frames.at(-1);const second=harness();const seeker=new StoryPlayer({id:'x',project:'x',steps:[{action:'activate',id:'A',cameraDuration:1}]},{searchable:[feature]} as unknown as ProjectData,second.operations);await seeker.seek(.5);expect(autoplay).toEqual(second.frames.at(-1));player.pause();vi.useRealTimers()})
 it('rejects non-finite public seek values and clamps negative values',async()=>{const {frames,operations}=harness();const player=new StoryPlayer({id:'x',project:'x',steps:[]},{searchable:[feature]} as unknown as ProjectData,operations);await expect(player.seek(NaN)).rejects.toThrow('finite');await player.seek(-2);expect(frames.at(-1)?.timeMs).toBe(0)})
})
