import { useCallback, useEffect, useMemo, useRef, useState, type MouseEvent } from 'react'
import type { ProjectData } from '../data/project'
import type { StoryPlayer, StoryPlayerState } from './storyPlayer'
import type { Story, StoryAppOperations, StoryStep } from './storyTypes'
import { DEFAULT_CAMERA_DURATION_MS } from './storyTimeline'
import { seekStoryPreview } from './storyTimingEditor'
import { layoutTimeline, timeToX } from './storyTimelineLayout'
import { createEditorModel, currentViewStep, deleteSelected, duplicateStep, insertStep, moveSelectedEarlier, moveSelectedLater, moveSelectedTo, selectOnly, selectRange, toggleSelection, toStory, updateStep } from './storyEditorState'
import { downloadStory, saveStoryToSource } from './storySerialization'

const ACTION_NAMES: Record<StoryStep['action'], string> = { show:'Show',hide:'Hide',activate:'Activate',deactivate:'Deactivate',wait:'Wait',setView:'View',setBasemap:'Basemap',setOverlay:'Overlay',setDarkMode:'Dark mode',setDarkBasemap:'Dark basemap',selectJurisdiction:'Jurisdiction',clearJurisdiction:'Clear jurisdiction',showJurisdiction:'Show region',activateJurisdiction:'Activate region',hideJurisdiction:'Hide region' }
const summary = (step: StoryStep, names: Map<string,string>) => { if ('snapshotDate' in step) return `${step.name} · ${step.snapshotDate.slice(0,4)}`; if ('id' in step) return names.get(step.id) ?? step.id; if (step.action === 'setView') return step.label ?? `${step.center[0].toFixed(4)}, ${step.center[1].toFixed(4)}`; if ('value' in step) return String(step.value); if (step.action === 'setOverlay') return `${step.layer} ${step.visible ? 'ON' : 'OFF'}`; return step.label ?? '' }
const numeric = (value: string) => Number(value)
const RATE_OPTIONS = [0.5,1,2,4]
const DURATION_PRESETS = [0.5,0.8,1,1.5,2]
const formatTime = (seconds:number) => seconds < 10 ? seconds.toFixed(1) : seconds.toFixed(0)

export function StoryEditor({ story, project, operations, player, state, onChange, onInsertReady }: { story: Story; project: ProjectData; operations: StoryAppOperations; player: StoryPlayer; state: StoryPlayerState; onChange(story: Story): void; onInsertReady?(insert:((step:StoryStep)=>void)|null):void }) {
  const [model,setModel]=useState(()=>createEditorModel(story)); const dragKeys=useRef<string[]>([])
  const modelRef=useRef(model); modelRef.current=model
  const [saveState,setSaveState]=useState<'idle'|'saving'|'saved'|'error'>('idle'); const [saveMessage,setSaveMessage]=useState('')
  const names=useMemo(()=>new Map(project.searchable.map(feature=>[feature.properties.id,feature.properties.name])),[project])
  const commit=useCallback((next:ReturnType<typeof createEditorModel>)=>{player.pause();modelRef.current=next;setModel(next);onChange(toStory(next));setSaveState('idle');setSaveMessage('')},[onChange,player])
  const insertExternal=useCallback((step:StoryStep)=>commit(insertStep(modelRef.current,step)),[commit])
  useEffect(()=>{onInsertReady?.(insertExternal);return()=>onInsertReady?.(null)},[insertExternal,onInsertReady])
  const selectedEntries=model.steps.filter(entry=>model.selectedKeys.includes(entry.key)); const selected=selectedEntries.length===1?selectedEntries[0]:undefined
  const selectedIndex=selected?model.steps.findIndex(entry=>entry.key===selected.key):-1
  const edit=(patch:Record<string,unknown>)=>selected&&commit(updateStep(model,selected.key,{...selected.step,...patch} as StoryStep))
  const save=async()=>{setSaveState('saving');setSaveMessage('');try{const result=await saveStoryToSource(toStory(model));setSaveState('saved');setSaveMessage(`Saved ${result.path}`)}catch(error){setSaveState('error');setSaveMessage(error instanceof Error?error.message:String(error))}}
  const presets=(apply:(duration:number)=>void)=><div className="story-duration-presets"><span>Presets</span>{DURATION_PRESETS.map(value=><button key={value} onClick={()=>apply(value)}>{value.toFixed(1)}</button>)}</div>
  const select=(event:MouseEvent,entryKey:string)=>setModel(current=>event.shiftKey?selectRange(current,entryKey):(event.metaKey||event.ctrlKey)?toggleSelection(current,entryKey):selectOnly(current,entryKey))
  const layout=layoutTimeline(player.timeline); const totalSeconds=player.getDuration(); const canvasWidth=Math.max(720,timeToX(player.timeline.durationMs)+180)
  const maxStack=Math.max(0,...layout.filter(item=>item.durationMs===0).map(item=>item.stack)); const flagHeight=Math.max(64,(maxStack+1)*26+18)
  const ticks=useMemo(()=>{const interval=totalSeconds>60?10:totalSeconds>20?5:1;const values:number[]=[];for(let value=0;value<totalSeconds;value+=interval)values.push(value);if(!values.includes(totalSeconds))values.push(totalSeconds);return values},[totalSeconds])
  const onDragStart=(key:string)=>{dragKeys.current=model.selectedKeys.includes(key)?model.selectedKeys:[key];if(!model.selectedKeys.includes(key))setModel(selectOnly(model,key))}
  const dropAt=(index:number)=>{const base={...modelRef.current,selectedKeys:dragKeys.current,selectionAnchorKey:dragKeys.current.at(-1)??null};commit(moveSelectedTo(base,index));dragKeys.current=[]}
  return <section className="story-editor" aria-label="Story timeline editor">
    <div className="story-toolbar"><strong>STORY — {story.displayName??story.id}</strong><button onClick={()=>void player.restart()}>Restart</button><button onClick={()=>void player.previous()}>Previous</button><button onClick={()=>state.status==='playing'?player.pause():void player.play()}>{state.status==='playing'?'Pause':'Play'}</button><select aria-label="Preview speed" value={state.playbackRate} onChange={event=>player.setPlaybackRate(Number(event.target.value))}>{RATE_OPTIONS.map(rate=><option key={rate} value={rate}>{rate}×</option>)}</select><button onClick={()=>void player.next()}>Next</button><output>{state.elapsedSeconds.toFixed(2)} / {totalSeconds.toFixed(2)} s</output><span className="story-toolbar-divider"/><button onClick={()=>commit(insertStep(model,currentViewStep(operations.getCurrentView())))}>+ Current View</button><button onClick={()=>commit(insertStep(model,{action:'wait',duration:2}))}>+ Wait</button><button disabled={!selected} onClick={()=>void player.previewStep(selectedIndex)}>Preview selected</button><button disabled={!selected} onClick={()=>void player.playFrom(selectedIndex)}>Preview from here</button><button disabled={!model.selectedKeys.length} onClick={()=>commit(moveSelectedEarlier(model))}>Move up</button><button disabled={!model.selectedKeys.length} onClick={()=>commit(moveSelectedLater(model))}>Move down</button><button disabled={!model.selectedKeys.length} onClick={()=>commit(deleteSelected(model))}>Delete</button><button disabled={saveState==='saving'} onClick={()=>void save()}>{saveState==='saving'?'Saving…':saveState==='saved'?'Saved ✓':'Save / Update Story'}</button><button onClick={()=>downloadStory(toStory(model))}>Download JSON</button></div>
    <div className="story-dock-body">
      <div className="story-timeline-viewport">
        <div className="story-timeline-canvas" style={{width:canvasWidth,height:flagHeight+91}} onDragOver={event=>event.preventDefault()} onDrop={()=>dropAt(model.steps.length)}>
          <div className="story-flags" style={{height:flagHeight}}>{layout.map(item=>{if(item.durationMs)return null;const entry=model.steps[item.stepIndex];return <button key={entry.key} className={`story-flag ${model.selectedKeys.includes(entry.key)?'selected':''}`} style={{left:timeToX(item.startMs),top:item.stack*26}} draggable onDragStart={()=>onDragStart(entry.key)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();dropAt(item.stepIndex)}} onClick={event=>select(event,entry.key)} title={`${ACTION_NAMES[entry.step.action]} ${summary(entry.step,names)}`}><i>{item.stepIndex+1}</i><span>{ACTION_NAMES[entry.step.action]} {summary(entry.step,names)}</span></button>})}</div>
          <div className="story-duration-lane">{layout.map(item=>{if(!item.durationMs)return null;const entry=model.steps[item.stepIndex];return <button key={entry.key} className={`story-duration-bar ${entry.step.action==='wait'?'wait':''} ${model.selectedKeys.includes(entry.key)?'selected':''}`} style={{left:timeToX(item.startMs),width:Math.max(46,timeToX(item.durationMs))}} draggable onDragStart={()=>onDragStart(entry.key)} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.stopPropagation();dropAt(item.stepIndex)}} onClick={event=>select(event,entry.key)}><b>{item.stepIndex+1}. {ACTION_NAMES[entry.step.action]}</b><small>{summary(entry.step,names)} · {(item.durationMs/1000).toFixed(1)}s</small></button>})}</div>
          <div className="story-ruler">{ticks.map(value=><span key={value} style={{left:timeToX(value*1000)}}><i/>{formatTime(value)}s</span>)}<input aria-label="Story time" type="range" min="0" max={totalSeconds||0.001} step="0.001" value={Math.min(state.elapsedSeconds,totalSeconds)} onChange={event=>void seekStoryPreview(player,Number(event.target.value))}/></div>
          <div className="story-playhead" style={{left:timeToX(state.elapsedSeconds*1000)}}><span>{state.elapsedSeconds.toFixed(2)}</span></div>
        </div>
      </div>
      <aside className="story-inspector"><h3>{selected?`${selectedIndex+1}. ${ACTION_NAMES[selected.step.action]}`:selectedEntries.length?`${selectedEntries.length} steps selected`:'Inspector'}</h3>{selected&&<p>{summary(selected.step,names)}</p>}{selected?.step.action==='activate'&&<><label>Target<input value={names.get(selected.step.id)??selected.step.id} readOnly/></label><label>Camera duration<input type="number" min="0" step="0.1" value={selected.step.cameraDuration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={event=>edit({cameraDuration:numeric(event.target.value)})}/></label>{presets(duration=>edit({cameraDuration:duration}))}</>}{selected?.step.action==='activateJurisdiction'&&<><label>Target<input value={`${selected.step.name} · ${selected.step.snapshotDate}`} readOnly/></label><label>Camera duration<input type="number" min="0" step="0.1" value={selected.step.cameraDuration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={event=>edit({cameraDuration:numeric(event.target.value)})}/></label>{presets(duration=>edit({cameraDuration:duration}))}</>}{selected?.step.action==='setView'&&<><label>Label<input value={selected.step.label??''} onChange={e=>edit({label:e.target.value||undefined})}/></label><label>Duration<input type="number" min="0" step="0.1" value={selected.step.duration??DEFAULT_CAMERA_DURATION_MS/1000} onChange={e=>edit({duration:numeric(e.target.value)})}/></label><div className="story-view-grid"><label>Lng<input type="number" step=".000001" value={(selected.step as Extract<StoryStep,{action:'setView'}>).center[0]} onChange={e=>edit({center:[numeric(e.target.value),(selected.step as Extract<StoryStep,{action:'setView'}>).center[1]]})}/></label><label>Lat<input type="number" step=".000001" value={(selected.step as Extract<StoryStep,{action:'setView'}>).center[1]} onChange={e=>edit({center:[(selected.step as Extract<StoryStep,{action:'setView'}>).center[0],numeric(e.target.value)]})}/></label><label>Zoom<input type="number" step=".001" value={selected.step.zoom} onChange={e=>edit({zoom:numeric(e.target.value)})}/></label><label>Bearing<input type="number" step=".01" value={selected.step.bearing} onChange={e=>edit({bearing:numeric(e.target.value)})}/></label><label>Pitch<input type="number" min="0" max="85" step=".01" value={selected.step.pitch} onChange={e=>edit({pitch:numeric(e.target.value)})}/></label></div>{presets(duration=>edit({duration}))}</>}{selected?.step.action==='wait'&&<><label>Duration<input type="number" min="0" step="0.1" value={selected.step.duration} onChange={e=>edit({duration:numeric(e.target.value)})}/></label>{presets(duration=>edit({duration}))}</>}{selected&&<button onClick={()=>commit(duplicateStep(model,selected.key))}>Duplicate</button>}{saveMessage&&<small className={saveState==='error'?'story-error':'story-save-status'}>{saveMessage}</small>}{state.error&&<em className="story-error">{state.error}</em>}</aside>
    </div>
  </section>
}
