import { describe, expect, it } from 'vitest'
import { createEditorModel, currentViewStep, insertStep, insertionIndex, moveSelectedEarlier, moveSelectedLater, moveSelectedTo, selectOnly, selectRange, toggleSelection, toStory, updateStep } from './storyEditorState'
const makeStory=()=>({id:'demo',project:'shinjuku',steps:['A','B','C','D','E'].map(id=>({action:'show' as const,id}))})
const ids=(model:ReturnType<typeof createEditorModel>)=>toStory(model).steps.map(step=>'id' in step?step.id:step.action)
describe('story editor state',()=>{
 it('supports single, toggle, and range selection by stable key',()=>{const initial=createEditorModel(makeStory());const one=selectOnly(initial,initial.steps[1].key);expect(one.selectedKeys).toEqual([initial.steps[1].key]);const added=toggleSelection(one,initial.steps[3].key);expect(added.selectedKeys).toEqual([initial.steps[1].key,initial.steps[3].key]);expect(toggleSelection(added,initial.steps[1].key).selectedKeys).toEqual([initial.steps[3].key]);const range=selectRange(one,initial.steps[4].key);expect(range.selectedKeys).toEqual(initial.steps.slice(1,5).map(entry=>entry.key))})
 it('moves one selection earlier and later',()=>{const initial=createEditorModel(makeStory());const selected=selectOnly(initial,initial.steps[2].key);expect(ids(moveSelectedEarlier(selected))).toEqual(['A','C','B','D','E']);expect(ids(moveSelectedLater(selected))).toEqual(['A','B','D','C','E'])})
 it('moves adjacent selections as a stable group',()=>{const initial=createEditorModel(makeStory());const selected={...initial,selectedKeys:[initial.steps[1].key,initial.steps[2].key],selectionAnchorKey:initial.steps[1].key};expect(ids(moveSelectedLater(selected))).toEqual(['A','D','B','C','E']);expect(ids(moveSelectedEarlier(selected))).toEqual(['B','C','A','D','E'])})
 it('moves non-contiguous selections without reversal, duplication, or loss',()=>{const initial=createEditorModel(makeStory());const keys=[initial.steps[1].key,initial.steps[3].key];const selected={...initial,selectedKeys:keys,selectionAnchorKey:keys[0]};const moved=moveSelectedTo(selected,5);expect(ids(moved)).toEqual(['A','C','E','B','D']);expect(moved.selectedKeys).toEqual(keys);expect(new Set(moved.steps.map(entry=>entry.key)).size).toBe(5)})
 it('inserts after the latest selected step and keeps metadata out of Story JSON',()=>{const initial=createEditorModel(makeStory());const selected={...initial,selectedKeys:[initial.steps[0].key,initial.steps[2].key],selectionAnchorKey:initial.steps[0].key};expect(insertionIndex(selected)).toBe(3);const inserted=insertStep(selected,{action:'wait',duration:4});expect(ids(inserted)).toEqual(['A','B','C','wait','D','E']);expect(Object.keys(toStory(inserted))).toEqual(['id','displayName','project','steps']);expect(JSON.stringify(toStory(inserted))).not.toContain('selectedKeys')})
 it('edits views and uses the fast authoring default',()=>{let model=createEditorModel({id:'x',project:'x',steps:[]});model=insertStep(model,currentViewStep({center:[139.7,35.6],zoom:15,bearing:1,pitch:2}));const entry=model.steps[0];const edited=updateStep(model,entry.key,{...(entry.step as Extract<typeof entry.step,{action:'setView'}>),duration:3});expect(toStory(edited).steps[0]).toMatchObject({action:'setView',duration:3,center:[139.7,35.6]})})
})
