import { describe, expect, it, vi } from 'vitest'
import type { ProjectData } from '../data/project'
import type { EntityFeature, LayerVisibility } from '../types/geo'
import { StoryPlayer, type StoryClock } from './storyPlayer'
import type { Story, StoryAppOperations, StoryAppSnapshot } from './storyTypes'

const entity=(id:string):EntityFeature=>({type:'Feature',properties:{id,name:id,type:'place'},geometry:{type:'Point',coordinates:[0,0]}})
const layers:LayerVisibility={basemap:'presentation',darkBasemap:false,modernRoads:false,railways:false,stations:false,historicalRoads:false,historicalPosts:false,jurisdictions:false}
function harness(steps:Story['steps']) {
  const a=entity('A'),b=entity('B');let snapshot:StoryAppSnapshot={selected:[a],activeFeature:null,basemap:'presentation',layers:{...layers},darkMode:'auto',jurisdiction:null};const calls:string[]=[]
  const operations:StoryAppOperations={snapshot:()=>structuredClone(snapshot),restore:(value)=>{snapshot=structuredClone(value);calls.push('restore')},showFeature:(f)=>{if(!snapshot.selected.some(x=>x.properties.id===f.properties.id))snapshot.selected.push(f);calls.push(`show:${f.properties.id}`)},hideFeature:(f)=>{snapshot.selected=snapshot.selected.filter(x=>x.properties.id!==f.properties.id);if(snapshot.activeFeature?.properties.id===f.properties.id)snapshot.activeFeature=null;calls.push(`hide:${f.properties.id}`)},activateFeature:(f,o)=>{snapshot.activeFeature=f;calls.push(`activate:${f.properties.id}:${o?.animateCamera}`)},deactivateFeature:()=>{snapshot.activeFeature=null},setBasemap:(v)=>{snapshot.layers.basemap=v;calls.push(`basemap:${v}`)},setOverlayVisibility:(k,v)=>{snapshot.layers[k]=v;calls.push(`overlay:${k}:${v}`)},setDarkMode:(v)=>{snapshot.darkMode=v},setManualDarkBasemap:(v)=>{snapshot.layers.darkBasemap=v},selectJurisdiction:(id,o)=>{snapshot.jurisdiction={level:'municipality',value:id};calls.push(`jurisdiction:${id}:${o?.animateCamera}`)},clearJurisdiction:()=>{snapshot.jurisdiction=null;calls.push('clearJurisdiction')}}
  return {player:new StoryPlayer({id:'test',project:'p',steps},{searchable:[a,b]} as ProjectData,operations),calls,getSnapshot:()=>snapshot}
}
describe('story player',()=>{
  it('executes state actions in order and preserves show/hide distinctions',async()=>{const {player,calls,getSnapshot}=harness([{action:'show',id:'A'},{action:'show',id:'A'},{action:'setOverlay',layer:'stations',visible:true},{action:'activate',id:'B',cameraDuration:1.5},{action:'hide',id:'A'}]);await player.play();expect(getSnapshot().selected).toEqual([]);expect(getSnapshot().activeFeature?.properties.id).toBe('B');expect(calls).toEqual(['show:A','show:A','overlay:stations:true','activate:B:undefined','hide:A']);expect(player.getState().status).toBe('complete')})
  it('stops on missing features',async()=>{const {player}=harness([{action:'show',id:'unknown'}]);await player.play();expect(player.getState()).toMatchObject({status:'error',error:'Story feature not found: unknown'})})
  it('restores baseline on restart',async()=>{const {player,getSnapshot}=harness([{action:'setBasemap',value:'gsi'},{action:'setDarkMode',value:'manual'},{action:'setDarkBasemap',value:true},{action:'selectJurisdiction',id:'j'}]);await player.play();await player.restart();expect(getSnapshot()).toMatchObject({darkMode:'auto',jurisdiction:null,layers:{basemap:'presentation',darkBasemap:false}});expect(getSnapshot().selected.map(x=>x.properties.id)).toEqual(['A'])})
  it('reconstructs previous state without intermediate camera animation',async()=>{const {player,calls,getSnapshot}=harness([{action:'setBasemap',value:'gsi'},{action:'activate',id:'B'},{action:'selectJurisdiction',id:'j'}]);await player.next();await player.next();await player.next();calls.length=0;await player.previous();expect(getSnapshot().activeFeature?.properties.id).toBe('B');expect(getSnapshot().jurisdiction).toBeNull();expect(calls).toContain('activate:B:false')})
  it('pauses and resumes with the remaining wait',async()=>{vi.useFakeTimers();let now=0;const clock:StoryClock={now:()=>now,schedule:(cb,ms)=>setTimeout(cb,ms),cancel:(id)=>clearTimeout(id as number)};const {calls,getSnapshot}=harness([]);const a=entity('A');const state:StoryAppSnapshot={selected:[],activeFeature:null,basemap:'presentation',layers:{...layers},darkMode:'auto',jurisdiction:null};const ops:StoryAppOperations={snapshot:()=>state,restore:()=>{},showFeature:()=>calls.push('show'),hideFeature:()=>{},activateFeature:()=>{},deactivateFeature:()=>{},setBasemap:()=>{},setOverlayVisibility:()=>{},setDarkMode:()=>{},setManualDarkBasemap:()=>{},selectJurisdiction:()=>{},clearJurisdiction:()=>{}};const player=new StoryPlayer({id:'x',project:'p',steps:[{action:'wait',duration:2},{action:'show',id:'A'}]},{searchable:[a]} as ProjectData,ops,clock);void player.play();now=750;vi.advanceTimersByTime(750);player.pause();vi.advanceTimersByTime(5000);expect(calls).toEqual([]);void player.play();vi.advanceTimersByTime(1249);await Promise.resolve();expect(calls).toEqual([]);vi.advanceTimersByTime(1);await vi.runAllTimersAsync();expect(calls).toEqual(['show']);expect(getSnapshot).toBeTypeOf('function');vi.useRealTimers()})
})
