import{useEffect,useState}from'react'
import{emptyProject,projectDeletionConfirmation,projectDeletionPath,projectIdPattern,projectSavePlan,ProjectConfig,ProjectSavePlan,ProjectLayer,ProjectVisibility,selectHistoricalRoute,toggleProjectLayer}from'./projectModel'
type Road={id:string;displayName:string;aliases:string[];built:boolean;presentationType:'road'|'historical-road'}
export type Route={routeId:string;name?:string;altName?:string;start?:string;end?:string;featureCount?:number}
export function HistoricalRouteRow({route,project,onChange}:{route:Route;project:ProjectConfig;onChange:(project:ProjectConfig)=>void}){return <div><label className="catalogItem"><input type="checkbox" checked={(project.layers.historicalRoads||[]).includes(route.routeId)} onChange={()=>onChange(selectHistoricalRoute(project,route.routeId))}/><span><strong>{route.name||route.routeId}</strong><small>{route.routeId}{route.start&&route.end?` · ${route.start} → ${route.end}`:''}</small>{route.altName&&<small>別名: {route.altName}</small>}</span></label><label className="posts"><input type="checkbox" checked={(project.layers.historicalPosts||[]).includes(route.routeId)} onChange={()=>onChange(toggleProjectLayer(project,'historicalPosts',route.routeId))}/>include 宿場</label></div>}
export function BuilderRoadRow({road,project,onChange}:{road:Road;project:ProjectConfig;onChange:(project:ProjectConfig)=>void}){return <label className="catalogItem"><input type="checkbox" checked={(project.layers.modernRoads||[]).includes(road.id)} onChange={()=>onChange(toggleProjectLayer(project,'modernRoads',road.id))}/><span>{road.displayName}<small>{road.id} · {road.built?'built':'not built ⚠'}{road.presentationType==='historical-road'?' · 歴史街道':''}</small></span></label>}
export function ProjectSaveActions({plan,onSave}:{plan:ProjectSavePlan;onSave:(build:boolean)=>void}){return <><button onClick={()=>onSave(false)}>{plan.saveLabel}</button><button className="primary" onClick={()=>onSave(true)}>{plan.buildLabel}</button></>}
export function ExistingProjectNotice({project}:{project:{id:string;displayName:string}}){return <p className="existing-project"><strong>Existing project: {project.id}</strong><br/>Saving will replace the existing project configuration.</p>}
type Catalog={modernRoads:Road[];historicalRoutes:Route[];availability:{codh:{ready:boolean;command:string};rail:{ready:boolean;command:string}}}
type Summary={manifest:{bounds:[number,number,number,number];featureCounts:Record<string,number>};counts:Record<string,number>}
const request=async(path:string,method='GET',project?:ProjectConfig)=>{const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:project?JSON.stringify({project}):undefined});const value=await response.json();if(!response.ok)throw new Error(value.error?.message||'Request failed');return value}
export default function ProjectEditor({onPreview,onClearPreview,visibility,onVisibility}:{onPreview:(value:{layers:Record<ProjectLayer,GeoJSON.FeatureCollection>;manifest:{bounds:[number,number,number,number]}})=>void;onClearPreview:()=>void;visibility:ProjectVisibility;onVisibility:(value:ProjectVisibility)=>void}){
 const[projects,setProjects]=useState<{id:string;displayName:string}[]>([]),[catalog,setCatalog]=useState<Catalog>(),[project,setProject]=useState(emptyProject()),[editing,setEditing]=useState<string>(),[search,setSearch]=useState(''),[historySearch,setHistorySearch]=useState(''),[status,setStatus]=useState('Ready'),[error,setError]=useState(''),[summary,setSummary]=useState<Summary>()
 const reload=()=>Promise.all([request('/api/projects'),request('/api/project-catalog')]).then(([p,c])=>{setProjects(p.projects);setCatalog(c)})
 useEffect(()=>{reload().catch(reason=>setError(reason.message))},[])
 const save=async(build:boolean)=>{setError('');if(!projectIdPattern.test(project.id)){setError('Project ID must use lowercase letters, numbers, and hyphens');return}const plan=projectSavePlan(project.id,projects.map(item=>item.id));try{setStatus(plan.existing?'Updating…':'Saving…');await request(plan.path,plan.method,project);setEditing(project.id);await reload();if(build){setStatus('Building…');const result=await request(`/api/projects/${project.id}/build`,'POST');setSummary(result);const preview=await request(`/api/projects/${project.id}/preview`);onPreview(preview);setStatus(plan.existing?'Project updated and built':'Project built')}else setStatus(plan.existing?'Project updated':'Project saved')}catch(reason){setError((reason as Error).message);setStatus('Failed')}}
 const deleteProject=async()=>{if(!editing)return;const existing=projects.find(item=>item.id===editing);if(!existing||!window.confirm(projectDeletionConfirmation(existing)))return;setError('');setStatus('Deleting…');try{await request(projectDeletionPath(editing),'DELETE');setProject(emptyProject());setEditing(undefined);setSummary(undefined);onClearPreview();await reload();setStatus(`Deleted ${existing.id}`)}catch(reason){setError((reason as Error).message);setStatus('Delete failed')}}
 const modern=catalog?.modernRoads.filter(item=>[item.id,item.displayName,...item.aliases].join(' ').toLowerCase().includes(search.toLowerCase()))||[]
 const routes=catalog?.historicalRoutes.filter(item=>[item.routeId,item.name,item.altName].join(' ').toLowerCase().includes(historySearch.toLowerCase()))||[]
 const explicitBounds=Array.isArray(project.bounds)?project.bounds:undefined
 const existingProject=projects.find(item=>item.id===project.id)
 const savePlan=projectSavePlan(project.id,projects.map(item=>item.id))
 return <section className="editor projectEditor"><header><h1>Project Authoring</h1><b>LOCAL DEVELOPMENT TOOL ONLY</b></header><div className="toolbar"><button onClick={()=>{setProject(emptyProject());setEditing(undefined);setSummary(undefined)}}>New project</button><select value={editing||''} onChange={async event=>{if(!event.target.value)return;const result=await request(`/api/projects/${event.target.value}`);setProject(result.project);setEditing(event.target.value);setSummary(undefined);try{onPreview(await request(`/api/projects/${event.target.value}/preview`))}catch{/* project may not be built yet */}}}><option value="">Load existing project…</option>{projects.map(item=><option key={item.id} value={item.id}>{item.displayName} — {item.id}</option>)}</select>{editing&&<button className="destructive" onClick={deleteProject}>Delete Project…</button>}</div>
 <label>Project ID<input value={project.id} disabled={Boolean(editing)} onChange={e=>setProject({...project,id:e.target.value})}/></label><label>Display name<input value={project.displayName} onChange={e=>setProject({...project,displayName:e.target.value})}/></label>{existingProject&&<ExistingProjectNotice project={existingProject}/>}
 <fieldset><legend>Builder roads</legend><input aria-label="Search builder roads" placeholder="Search roads" value={search} onChange={e=>setSearch(e.target.value)}/>{modern.map(road=><BuilderRoadRow road={road} project={project} onChange={setProject} key={road.id}/>)}</fieldset>
 <fieldset><legend>Supporting layers</legend><label className="inline"><input type="checkbox" checked={Boolean(project.layers.railways)} onChange={()=>setProject(toggleProjectLayer(project,'railways'))}/>Railways</label>{project.layers.railways?.mode==='near-modern-roads'&&<><small>Include complete railway lines near selected roads</small><label>Distance (km)<input type="number" min="0.1" value={project.layers.railways.distanceKm} onChange={e=>setProject({...project,layers:{...project.layers,railways:{mode:'near-modern-roads',distanceKm:Number(e.target.value)}}})}/></label></>}<label className="inline"><input type="checkbox" checked={Boolean(project.layers.stations)} onChange={()=>setProject(toggleProjectLayer(project,'stations'))}/>Stations</label><p>{catalog?.availability.rail.ready?'Rail cache: ready':<>Rail cache missing<br/>Run: {catalog?.availability.rail.command}</>}</p></fieldset>
 <fieldset><legend>Historical routes</legend>{!catalog?.availability.codh.ready&&<p>Historical routes unavailable<br/>Run: {catalog?.availability.codh.command}</p>}<input aria-label="Search historical routes" placeholder="Search route ID or name" value={historySearch} onChange={e=>setHistorySearch(e.target.value)}/>{routes.map(route=><HistoricalRouteRow key={route.routeId} route={route} project={project} onChange={setProject}/>)}</fieldset>
 <fieldset><legend>Bounds</legend><label><input type="radio" checked={!Array.isArray(project.bounds)} onChange={()=>setProject({...project,bounds:{mode:'auto',from:'modernRoads',paddingKm:3}})}/> Automatic from modern roads</label>{!Array.isArray(project.bounds)&&<label>Padding (km)<input type="number" min="0.1" value={project.bounds.paddingKm} onChange={e=>setProject({...project,bounds:{...project.bounds as Exclude<ProjectConfig['bounds'],number[]>,paddingKm:Number(e.target.value)}})}/></label>}<label><input type="radio" checked={Array.isArray(project.bounds)} onChange={()=>setProject({...project,bounds:[139,35,140,36]})}/> Explicit bbox</label>{explicitBounds&&<div className="bbox">{['west','south','east','north'].map((name,index)=><label key={name}>{name}<input type="number" value={explicitBounds[index]} onChange={e=>{const bounds=[...explicitBounds]as[number,number,number,number];bounds[index]=Number(e.target.value);setProject({...project,bounds})}}/></label>)}</div>}</fieldset>
 <div className="actions"><ProjectSaveActions plan={savePlan} onSave={save}/></div><p className="status">{status}</p>{error&&<p className="error">{error}</p>}{summary&&<section className="buildResult"><h3>Project built</h3>{Object.entries(summary.counts).map(([key,value])=><div key={key}>{key}: {value}</div>)}<p>Resolved bounds: [{summary.manifest.bounds.join(', ')}]</p><a href={`http://localhost:5173/?project=${project.id}`} target="_blank">Open in site: ?project={project.id}</a></section>}
 <fieldset><legend>Preview layers</legend>{(['modernRoads','railways','stations','historicalRoads','historicalPosts']as ProjectLayer[]).map(id=><label className="inline" key={id}><input type="checkbox" checked={visibility[id]} onChange={()=>onVisibility({...visibility,[id]:!visibility[id]})}/>{id==='historicalPosts'?'宿場':id}</label>)}</fieldset></section>
}
