import{renderToStaticMarkup}from'react-dom/server'
import{describe,expect,it}from'vitest'
import{BuilderRoadRow,ExistingProjectNotice,HistoricalRouteRow,ProjectLocationRow,ProjectSaveActions}from'./ProjectEditor'
import{emptyProject,projectDeletionConfirmation,projectDeletionPath,projectSavePlan}from'./projectModel'
describe('historical route catalog row',()=>{it('renders the API route ID, name, endpoints and alias without dash placeholders',()=>{const html=renderToStaticMarkup(<HistoricalRouteRow route={{routeId:'R003',name:'甲州道中',altName:'甲州街道',start:'江戸',end:'下諏訪'}} project={emptyProject()} onChange={()=>{}}/>);expect(html).toContain('甲州道中');expect(html).toContain('R003');expect(html).toContain('江戸 → 下諏訪');expect(html).toContain('別名: 甲州街道');expect(html).not.toContain('—</')})})
describe('builder road catalog row',()=>{it('shows historical classification while retaining modernRoads selection',()=>{const project={...emptyProject(),layers:{modernRoads:['custom-history']}};const html=renderToStaticMarkup(<BuilderRoadRow road={{id:'custom-history',displayName:'甲州道中',aliases:[],built:true,presentationType:'historical-road'}} project={project} onChange={()=>{}}/>);expect(html).toContain('built · 歴史街道');expect(html).toContain('checked')})})
describe('project save actions',()=>{
 it('shows create labels for a genuinely new ID',()=>{const html=renderToStaticMarkup(<ProjectSaveActions plan={projectSavePlan('new-project',['shinjuku'])} onSave={()=>{}}/>);expect(html).toContain('Save Project');expect(html).toContain('Save &amp; Build');expect(html).not.toContain('Update Project')})
 it('shows update labels and an overwrite notice for an existing exact ID',()=>{const plan=projectSavePlan('shinjuku',['shinjuku']);const html=renderToStaticMarkup(<><ExistingProjectNotice project={{id:'shinjuku',displayName:'新宿'}}/><ProjectSaveActions plan={plan} onSave={()=>{}}/></>);expect(html).toContain('Existing project: shinjuku');expect(html).toContain('replace the existing project configuration');expect(html).toContain('Update Project');expect(html).toContain('Update &amp; Build')})
})
describe('project deletion',()=>{it('uses the exact project API path and warns about configuration and preview removal',()=>{expect(projectDeletionPath('shinjuku')).toBe('/api/projects/shinjuku');const message=projectDeletionConfirmation({id:'shinjuku',displayName:'新宿'});expect(message).toContain('Delete 新宿?');expect(message).toContain('shinjuku');expect(message).toContain('built preview output');expect(message).toContain('Shared road and source data will not be deleted')})})

describe('location catalog row',()=>{it('selects a canonical location independently',()=>{const html=renderToStaticMarkup(<ProjectLocationRow location={{id:'shinjuku-oiwake',displayName:'新宿追分',presentationType:'reveal-area'}} project={{...emptyProject(),layers:{...emptyProject().layers,locations:['shinjuku-oiwake']}}} onChange={()=>{}}/>);expect(html).toContain('新宿追分');expect(html).toContain('reveal area');expect(html).toContain('checked')})})
