import { afterEach, describe, expect, it, vi } from 'vitest'
import type { JurisdictionFeature } from '../data/jurisdictions'
import { JURISDICTION_EMPHASIS_DURATION, jurisdictionDimFilter, jurisdictionLabelCollection, jurisdictionLabelOpacity, jurisdictionLabelText, updateJurisdictionEmphasis } from './jurisdictionEmphasis'
import { SOURCE_IDS } from './config'

const polygon=(id:string,name:string,parent?:string,size=1,x=0):JurisdictionFeature=>({type:'Feature',properties:{jurisdictionId:id,snapshotDate:'1924-12-31',prefectureName:'東京府',parentJurisdictionName:parent,municipalityName:name,sourceProvider:'Geoshape',sourceDataset:'historical'},geometry:{type:'Polygon',coordinates:[[[x,0],[x+size,0],[x+size,size],[x,size],[x,0]]]}})

afterEach(()=>vi.unstubAllGlobals())
describe('jurisdiction spotlight helpers',()=>{
  it('excludes every selected jurisdiction ID from the dim veil',()=>expect(jurisdictionDimFilter([polygon('ward-a','A'),polygon('ward-b','B')])).toEqual(['!', ['in',['get','jurisdictionId'],['literal',['ward-a','ward-b']]]]))
  it('disables dark emphasis when there is no selection',()=>expect(jurisdictionDimFilter([])).toEqual(['==',['literal',false],true]))
  it('formats municipality, standalone, and parent labels without blank text',()=>{expect(jurisdictionLabelText(polygon('wada','和田堀内村','豊多摩郡'),{level:'municipality',value:'和田堀内村'})).toEqual({parent:'豊多摩郡',primary:'和田堀内村'});expect(jurisdictionLabelText(polygon('adachi','足立区'),{level:'municipality',value:'足立区'})).toEqual({primary:'足立区'});expect(jurisdictionLabelText(polygon('tokyo','東京市'),{level:'parent',value:'東京市'})).toEqual({primary:'東京市'})})
  it('produces exactly one Point for a large polygon',()=>{const labels=jurisdictionLabelCollection([polygon('large','和田堀内村','豊多摩郡',100)],{level:'municipality',value:'和田堀内村'});expect(labels.features).toHaveLength(1);expect(labels.features[0].geometry.type).toBe('Point')})
  it('uses only the largest component of a MultiPolygon',()=>{const feature=polygon('islands','島町');feature.geometry={type:'MultiPolygon',coordinates:[[[[0,0],[1,0],[1,1],[0,1],[0,0]]],[[[10,0],[14,0],[14,4],[10,4],[10,0]]]]};const labels=jurisdictionLabelCollection([feature],{level:'municipality',value:'島町'});expect(labels.features).toHaveLength(1);expect(labels.features[0].geometry.coordinates[0]).toBeGreaterThan(10)})
  it('produces one parent label for 33 ward features',()=>{const wards=Array.from({length:33},(_,index)=>polygon(`ward-${index}`,`区${index}`,'東京市',index+1,index*40));const labels=jurisdictionLabelCollection(wards,{level:'parent',value:'東京市'});expect(labels.features).toHaveLength(1);expect(labels.features[0].properties).toMatchObject({primary:'東京市',selectionKey:'parent:東京市'});expect(labels.features[0].properties.parent).toBeUndefined()})
  it('produces no Point without a selection and replaces the prior label',()=>{expect(jurisdictionLabelCollection([],null).features).toHaveLength(0);const oldLabel=jurisdictionLabelCollection([polygon('old','Old')],{level:'municipality',value:'Old'});const nextLabel=jurisdictionLabelCollection([polygon('new','New',undefined,1,5)],{level:'municipality',value:'New'});expect(nextLabel.features).toHaveLength(1);expect(nextLabel.features[0].properties.selectionKey).toBe('municipality:New');expect(nextLabel).not.toContain(oldLabel.features[0])})
  it('sets one stable Point and fades its paint opacity exactly once',()=>{const frames:FrameRequestCallback[]=[];vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>{frames.push(callback);return frames.length});vi.stubGlobal('cancelAnimationFrame',vi.fn());vi.spyOn(performance,'now').mockReturnValue(0);const polygonSet=vi.fn(),labelSet=vi.fn(),setPaintProperty=vi.fn();const map={setFilter:vi.fn(),setPaintProperty,getSource:(id:string)=>id===SOURCE_IDS.jurisdictionHighlight?{setData:polygonSet}:{setData:labelSet}};updateJurisdictionEmphasis(map as never,[polygon('wada','和田堀内村','豊多摩郡')],{level:'municipality',value:'和田堀内村'});expect(labelSet).toHaveBeenCalledTimes(1);expect(labelSet.mock.calls[0][0].features).toHaveLength(1);expect(setPaintProperty).toHaveBeenLastCalledWith('jurisdiction-highlight-label','text-opacity',0);frames.shift()?.(JURISDICTION_EMPHASIS_DURATION*0.2);expect(setPaintProperty).toHaveBeenLastCalledWith('jurisdiction-highlight-label','text-opacity',0);frames.shift()?.(JURISDICTION_EMPHASIS_DURATION*0.5);expect(jurisdictionLabelOpacity(0.5)).toBeGreaterThan(0);expect(jurisdictionLabelOpacity(0.5)).toBeLessThan(1);expect(setPaintProperty).toHaveBeenLastCalledWith('jurisdiction-highlight-label','text-opacity',jurisdictionLabelOpacity(0.5));frames.shift()?.(JURISDICTION_EMPHASIS_DURATION);expect(setPaintProperty).toHaveBeenLastCalledWith('jurisdiction-highlight-label','text-opacity',1);expect(labelSet).toHaveBeenCalledTimes(1);expect(polygonSet).toHaveBeenCalledTimes(1)})
})
