import type { JurisdictionCollection, JurisdictionLayerConfig, JurisdictionManifest, JurisdictionSelection } from '../data/jurisdictions'

interface Props { manifest:JurisdictionManifest|null; collection:JurisdictionCollection|null; value:JurisdictionLayerConfig; loading:boolean; error:string|null; onChange:(value:JurisdictionLayerConfig)=>void }
export function JurisdictionPanel({manifest,collection,value,loading,error,onChange}:Props){
 const provider=manifest?.providers[value.provider];const prefecture=provider?.prefectures[value.prefecture]
 const municipalities=[...new Set(collection?.features.map(feature=>feature.properties.municipalityName)??[])].sort()
 const parents=[...new Set(collection?.features.flatMap(feature=>[feature.properties.parentJurisdictionName,feature.properties.jurisdictionLevel==='parent'?feature.properties.municipalityName:undefined]).filter((name):name is string=>Boolean(name))??[])].sort()
 const setSelection=(level:'municipality'|'parent',selected:string)=>onChange({...value,selection:selected?{level,value:selected}:null})
 return <section className="panel-section jurisdiction-panel"><div className="section-heading"><span className="eyebrow">HISTORICAL JURISDICTIONS</span><h2>歴史的行政区域</h2></div><label className="layer-row"><span className="layer-swatch jurisdictions"/><span><strong>区域を表示</strong><small>道路レイヤーとは独立</small></span><input type="checkbox" checked={value.enabled} onChange={()=>onChange({...value,enabled:!value.enabled})}/><i/></label><label className="jurisdiction-field">Provider<select value={value.provider} disabled><option value="geoshape">{provider?.displayName??'Geoshape'}</option></select></label><label className="jurisdiction-field">Prefecture<select value={value.prefecture} disabled><option value="13">{prefecture?.displayName??'Tokyo'}</option></select></label><label className="jurisdiction-field">Date<select aria-label="Jurisdiction snapshot date" value={value.snapshotDate??''} disabled={!prefecture||loading} onChange={event=>onChange({...value,snapshotDate:event.target.value,selection:value.selection?.level==='parent'?value.selection:null})}><option value="" disabled>Choose snapshot</option>{prefecture?.availableDates.map(date=><option key={date}>{date}</option>)}</select></label><label className="jurisdiction-field">表示単位<select aria-label="Jurisdiction display mode" value={value.displayMode} disabled={loading} onChange={event=>onChange({...value,displayMode:event.target.value as JurisdictionLayerConfig['displayMode'],selection:value.selection?.level==='parent'?value.selection:null})}><option value="municipality">市区町村</option><option value="parent-city">親自治体で統合（区のみ）</option></select></label><label className="jurisdiction-field">Highlight<select aria-label="Jurisdiction highlight" value={value.selection?`${value.selection.level}:${value.selection.value}`:''} disabled={!collection} onChange={event=>{const [level,...rest]=event.target.value.split(':');setSelection(level as NonNullable<JurisdictionSelection>['level'],rest.join(':'))}}><option value="">None</option><optgroup label="Municipality">{municipalities.map(name=><option key={`municipality:${name}`} value={`municipality:${name}`}>{name}</option>)}</optgroup><optgroup label="Parent jurisdiction">{parents.map(name=><option key={`parent:${name}`} value={`parent:${name}`}>{name}</option>)}</optgroup></select></label>{loading&&<p className="jurisdiction-status">Loading jurisdiction snapshot…</p>}{error&&<p className="jurisdiction-status error" role="alert">{error}</p>}<p className="jurisdiction-attribution">Geoshape 歴史的行政区域データセットβ版<br/>史料間で境界が異なる場合がある復元データです。</p></section>
}
