import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react'
import maplibregl from 'maplibre-gl'
import type { ProjectData } from '../data/project'
import type { EntityFeature, HighlightStyle, LayerVisibility, PointOverlayStyle, RoadSourceVisibility, SelectionMode } from '../types/geo'
import { createMap } from '../map/createMap'
import { addDataLayers, getPresentationLayerIds, setBasemapMode, setProjectLayerVisibility, updatePointOverlayStyle } from '../map/layers'
import { selectFeatures, updateHighlightStyle, updateLineLabelAnchors } from '../map/highlight'
import { LAYER_IDS, SOURCE_IDS } from '../map/config'
import { addRekichizuBasemap } from '../map/rekichizu'
import type { JurisdictionCollection, JurisdictionFeature, JurisdictionSelection } from '../data/jurisdictions'
import { updateJurisdictionEmphasis, updateJurisdictionEmphasisStyle } from '../map/jurisdictionEmphasis'
import type { GeoJSONSource } from 'maplibre-gl'
import { handleJurisdictionClick } from './jurisdictionClick'


export interface MapHandle { getMap: () => maplibregl.Map | null }
interface Props { project: ProjectData | null; selected: EntityFeature[]; activeFeature:EntityFeature|null; selectionMode:SelectionMode; jurisdictionData:JurisdictionCollection|null; jurisdictionHighlight:JurisdictionFeature[]; jurisdictionSelection:JurisdictionSelection; highlightStyle: HighlightStyle; presentationScale: number; visibility: LayerVisibility; darkBasemap:boolean; pointStyle: PointOverlayStyle; roadSources: RoadSourceVisibility; onSelectFeature: (feature:EntityFeature)=>void; onSelectJurisdiction:(feature:JurisdictionFeature)=>void; onReady: () => void }
export const MapView = forwardRef<MapHandle, Props>(function MapView({ project, selected, activeFeature, selectionMode, jurisdictionData, jurisdictionHighlight, jurisdictionSelection, highlightStyle, presentationScale, visibility, darkBasemap, pointStyle, roadSources, onSelectFeature,onSelectJurisdiction, onReady }, ref) {
  const container = useRef<HTMLDivElement>(null); const visibilityRef=useRef(visibility);const darkBasemapRef=useRef(darkBasemap);const pointStyleRef=useRef(pointStyle);const glowRef=useRef(highlightStyle.glow);const highlightStyleRef=useRef(highlightStyle);const presentationScaleRef=useRef(presentationScale);const selectedRef=useRef(selected);const activeFeatureRef=useRef(activeFeature);const roadSourcesRef=useRef(roadSources);const selectionModeRef=useRef(selectionMode);visibilityRef.current=visibility;darkBasemapRef.current=darkBasemap;pointStyleRef.current=pointStyle;glowRef.current=highlightStyle.glow;highlightStyleRef.current=highlightStyle;presentationScaleRef.current=presentationScale;selectedRef.current=selected;activeFeatureRef.current=activeFeature;roadSourcesRef.current=roadSources;selectionModeRef.current=selectionMode; const mapRef = useRef<maplibregl.Map | null>(null); const presentationLayerIds = useRef<string[]>([]); const rekichizuLayerIds = useRef<string[]>([]); const rekichizuLoad = useRef<Promise<string[]> | null>(null); const previousSelection = useRef<string[]>([])
  useImperativeHandle(ref, () => ({ getMap: () => mapRef.current }), [])
  useEffect(() => { if (!container.current || !project) return; const map = createMap(container.current); mapRef.current = map; const refreshLineLabels=()=>{if(map.isStyleLoaded()&&map.getSource(SOURCE_IDS.highlightLineLabels))updateLineLabelAnchors(map,selectedRef.current,roadSourcesRef.current,activeFeatureRef.current,selectionModeRef.current,highlightStyleRef.current,presentationScaleRef.current)}; map.on('moveend',refreshLineLabels);map.on('zoomend',refreshLineLabels);map.on('resize',refreshLineLabels); map.addControl(new maplibregl.NavigationControl({ showCompass: true }), 'bottom-left'); map.addControl(new maplibregl.AttributionControl({ compact: true }), 'bottom-right'); map.on('load', () => { presentationLayerIds.current = getPresentationLayerIds(map); addDataLayers(map, project); updateHighlightStyle(map,highlightStyleRef.current,presentationScaleRef.current); setProjectLayerVisibility(map,visibilityRef.current); updatePointOverlayStyle(map,pointStyleRef.current);selectFeatures(map,selectedRef.current,roadSourcesRef.current,activeFeatureRef.current,selectionModeRef.current,undefined,false,highlightStyleRef.current,presentationScaleRef.current); const inspect = [LAYER_IDS.modernRoads,LAYER_IDS.railways,LAYER_IDS.stations,LAYER_IDS.historicalRoads,LAYER_IDS.historicalPosts]; inspect.forEach((id) => map.on('click', id, (event) => { const clicked=event.features?.[0] as unknown as EntityFeature|undefined; if(!clicked)return; const p=clicked.properties; const routeIds=p.railRouteIds??[]; const selectable=project.searchable.find(feature=>routeIds.some(routeId=>feature.properties.railRouteIds?.includes(routeId)))??(p.railColorId?project.searchable.find(feature=>feature.properties.id===`railway:catalog:${p.railColorId}`):undefined)??clicked; onSelectFeature(selectable); const detail=[p.routeId,p.postId,p.historicalLabel,p.start&&p.end?`${p.start} → ${p.end}`:null,p.operator,p.network].filter(Boolean).join('<br>'); new maplibregl.Popup().setLngLat(event.lngLat).setHTML(`<strong>${p.railDisplayName??p.name??'名称不明'}</strong>${detail?`<br>${detail}`:''}`).addTo(map) })); map.on('click',LAYER_IDS.jurisdictionFill,event=>handleJurisdictionClick(event,onSelectJurisdiction)); onReady() }); return () => { map.off('moveend',refreshLineLabels);map.off('zoomend',refreshLineLabels);map.off('resize',refreshLineLabels);map.remove(); mapRef.current = null;rekichizuLoad.current=null;rekichizuLayerIds.current=[] } }, [onReady, onSelectFeature,onSelectJurisdiction, project])
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded() || !map.getSource(SOURCE_IDS.highlight)) return; const focus = selected.find((feature) => !previousSelection.current.includes(feature.properties.id)); previousSelection.current = selected.map((feature) => feature.properties.id); selectFeatures(map, selected, roadSources, activeFeature, selectionMode, focus, highlightStyle.animate, highlightStyle, presentationScale) }, [selected, activeFeature, selectionMode, roadSources, highlightStyle.animate])
  useEffect(() => { const map = mapRef.current; if (map?.isStyleLoaded() && map.getLayer(LAYER_IDS.highlightLine)) { map.resize(); updateHighlightStyle(map, highlightStyle, presentationScale); updateLineLabelAnchors(map,selectedRef.current,roadSourcesRef.current,activeFeatureRef.current,selectionModeRef.current,highlightStyle,presentationScale); updateJurisdictionEmphasisStyle(map,highlightStyle) } }, [highlightStyle, presentationScale])
  useEffect(() => { const map = mapRef.current; if (!map || !map.getLayer(LAYER_IDS.gsiBase)) return; setProjectLayerVisibility(map, visibility); if(visibility.basemap==='rekichizu'&&!rekichizuLayerIds.current.length){if(!rekichizuLoad.current)rekichizuLoad.current=addRekichizuBasemap(map,LAYER_IDS.whiteBase).then((ids)=>{rekichizuLayerIds.current=ids;if(visibilityRef.current.basemap==='rekichizu')setBasemapMode(map,'rekichizu',presentationLayerIds.current,ids,darkBasemapRef.current);return ids}).catch((error)=>{rekichizuLoad.current=null;console.warn('Rekichizu basemap is unavailable',error);return []});return} setBasemapMode(map, visibility.basemap, presentationLayerIds.current,rekichizuLayerIds.current,darkBasemap) }, [visibility, darkBasemap])
  useEffect(() => { const map=mapRef.current;if(map?.isStyleLoaded()&&map.getLayer(LAYER_IDS.stations))updatePointOverlayStyle(map,pointStyle) },[pointStyle])
  useEffect(()=>{const map=mapRef.current;if(!map?.isStyleLoaded())return;(map.getSource(SOURCE_IDS.jurisdictions) as GeoJSONSource|undefined)?.setData(jurisdictionData??{type:'FeatureCollection',features:[]});if(map.getSource(SOURCE_IDS.jurisdictionHighlight))updateJurisdictionEmphasis(map,jurisdictionHighlight,jurisdictionSelection,glowRef.current)},[jurisdictionData,jurisdictionHighlight,jurisdictionSelection])
  return <div ref={container} className="map" aria-label="東京周辺の歴史地図" />
})
