import { useMemo, useState } from 'react'
import { searchEntities } from '../search/search'
import type { EntityFeature, MapEntityType, SceneItem } from '../types/geo'

const typeNames: Record<string, string> = { road: '現代道路', 'historical-road': '歴史街道', place: '現代地名', 'historical-place': '宿場', station: '駅', chome: '町丁目' }
const depth: Record<MapEntityType, number> = { chome: 0, water: 0, 'terrain-feature': 0, jurisdiction:0, road: 1, 'historical-road': 1, railway: 1, river: 1, place: 2, 'historical-place': 2, station: 2, custom: 2 }

interface Props { entities: EntityFeature[]; loading: boolean; loadError: boolean; items: SceneItem[]; onToggle: (feature: EntityFeature) => void; onDelete: (id: string) => void; onClear: () => void }

export function SearchPanel({ entities, loading, loadError, items, onToggle, onDelete, onClear }: Props) {
  const [query, setQuery] = useState('')
  const results = useMemo(() => searchEntities(entities, query), [entities, query])
  const orderedItems = [...items].sort((left, right) => depth[left.feature.properties.type] - depth[right.feature.properties.type])
  return <section className="panel-section search-section"><div className="section-heading"><span className="eyebrow">FIND</span><h2>地物を探す</h2></div><label htmlFor="search" className="sr-only">道路・駅・宿場を検索</label><div className="search-box"><span aria-hidden="true">⌕</span><input id="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="甲州街道、内藤新宿…" autoComplete="off" /></div>{loading && <p className="search-status">プロジェクトを読み込み中…</p>}{loadError && <p className="search-status error">プロジェクトデータを読み込めませんでした。</p>}{query && <div className="search-results" aria-live="polite">{results.length ? results.map((feature) => { const item = items.find((candidate) => candidate.feature.properties.id === feature.properties.id); const active = item?.visible ?? false; return <button className={`result ${active ? 'active' : ''} ${item ? 'retained' : ''}`} key={feature.properties.id} onClick={() => onToggle(feature)} aria-pressed={active}><i className="result-check" aria-hidden="true">{active ? '✓' : ''}</i><span><strong>{feature.properties.name}</strong><small>{typeNames[feature.properties.type] ?? feature.properties.type}</small></span>{feature.properties.aliases?.length ? <em>{feature.properties.aliases.join('・')}</em> : null}</button> }) : <p className="empty">一致する地物がありません</p>}</div>}{!query && <div className="suggestions"><span>試す</span>{['甲州街道', '甲州道中', '内藤新宿', '新宿'].map((suggestion) => <button key={suggestion} onClick={() => setQuery(suggestion)}>{suggestion}</button>)}</div>}{orderedItems.length > 0 && <div className="selected-layers"><div className="selected-heading"><span className="eyebrow">SCENE LAYERS · 面 → 線 → 点</span><button type="button" onClick={onClear}>Clear scenes</button></div>{orderedItems.map(({ feature, visible, projectBacked }) => <div className={`scene-layer-row ${visible ? '' : 'muted'}`} key={feature.properties.id}><label><input type="checkbox" checked={visible} onChange={() => onToggle(feature)}/><i aria-hidden="true">{visible ? '✓' : ''}</i><span><strong>{feature.properties.name}</strong><small>{typeNames[feature.properties.type]}{projectBacked ? ' · Project' : ''}</small></span></label>{!projectBacked && <button className="delete-layer" type="button" aria-label={`${feature.properties.name}をsceneから削除`} onClick={() => onDelete(feature.properties.id)}>×</button>}</div>)}</div>}</section>
}
