import { useCallback, useRef, useState } from 'react'
import { CameraPanel } from './components/CameraPanel'
import { DataPanel } from './components/DataPanel'
import { LayerPanel } from './components/LayerPanel'
import { MapView, type MapHandle } from './components/MapView'
import { SearchPanel } from './components/SearchPanel'
import { StylePanel } from './components/StylePanel'
import { exportPNG } from './export/exportPNG'
import type { EntityFeature, HighlightStyle, LayerVisibility } from './types/geo'

export default function App(){ const mapRef=useRef<MapHandle>(null);const [selected,setSelected]=useState<EntityFeature|null>(null);const [ready,setReady]=useState(false);const [mobileOpen,setMobileOpen]=useState(false);const [style,setStyle]=useState<HighlightStyle>({color:'#087f72',width:7,opacity:1});const [layers,setLayers]=useState<LayerVisibility>({base:true,roads:true,historicalRoads:true,places:true,chome:true});const onReady=useCallback(()=>setReady(true),[]);return <main className="app"><header><div className="brand-mark">道</div><div className="brand"><strong>MICHI MAP</strong><span>Historical scene editor</span></div><div className="header-context"><span>PROJECT</span><b>新宿は何が新しかったのか</b></div><button className="mobile-toggle" onClick={()=>setMobileOpen(!mobileOpen)}>編集パネル</button><button className="export" disabled={!ready} onClick={()=>{const map=mapRef.current?.getMap();if(map)exportPNG(map)}}><span>↓</span> PNGを書き出す</button></header><div className="workspace"><div className="map-stage"><MapView ref={mapRef} selected={selected} highlightStyle={style} visibility={layers} onReady={onReady}/><div className="map-title"><span>35.690° N — 139.704° E</span><h1>東京・新宿</h1><p>地理院地図に現代と江戸の道筋を重ねて比較</p></div>{selected&&<aside className="selection-card"><span className="eyebrow">SELECTED</span><h3>{selected.properties.name}</h3><p>{selected.properties.period ?? '現代'} · 信頼度 {selected.properties.confidence}</p><small>{selected.properties.note}</small></aside>}<div className="legend"><span><i className="modern"/>現代道路</span><span><i className="historic"/>歴史街道</span><span><i className="point"/>宿場・地名</span></div></div><aside className={`sidebar ${mobileOpen?'open':''}`}><SearchPanel onSelect={(f)=>{setSelected(f);setMobileOpen(false)}}/><LayerPanel value={layers} onChange={setLayers}/><StylePanel value={style} onChange={setStyle}/><CameraPanel getMap={()=>mapRef.current?.getMap()??null}/><DataPanel/><footer>地図: 国土地理院 · Overlay: sample <span>v0.2-alpha</span></footer></aside></div></main>}
